#pragma config(Sensor, in1,    potLeft,        sensorPotentiometer)
#pragma config(Sensor, in2,    potRight,       sensorPotentiometer)
#pragma config(Motor,  port1,           strafeLeft,    tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           leftFront,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           leftBack,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightFront,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rightBack,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           liftLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           liftRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           intakeLeft,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           intakeRight,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          strafeRight,   tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	int liftSpeed = 0;
	int intakeSpeed = 0;
	while(1==1){

		if (vexRT[Btn6D] == 1){
    	liftSpeed = -127;
    } else if (vexRT[Btn6U] == 1){
    	liftSpeed = 127;
   	} else {
   		liftSpeed = 0;
   	}
    motor[liftLeft] = liftSpeed;
		motor[liftRight] = liftSpeed;

    if (vexRT[Btn5D] == 1){
    	intakeSpeed = -127;
    } else if (vexRT[Btn5U] == 1){
    	intakeSpeed = 127;
   	} else {
   		intakeSpeed = 0;
   	}
   	motor[intakeLeft] = intakeSpeed;
   	motor[intakeRight] = intakeSpeed;

   	motor[leftFront] = vexRT[Ch2] + vexRT[Ch1];
		motor[leftBack] = vexRT[Ch2] + vexRT[Ch1];

   	motor[rightFront] = vexRT[Ch2] - vexRT[Ch1];
		motor[rightBack] = vexRT[Ch2] - vexRT[Ch1];

		motor[strafeLeft] = vexRT[Ch4];
		motor[strafeRight] = vexRT[Ch4];
	}
}
